import { Public_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import RqWrapper from "@/components/RqWrapper";

const public_sans = Public_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Countries",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
              <RqWrapper>
      <body className={public_sans.className}>

      <Navbar />
 
        <section className="mainContainerSection flex items-center justify-center h-full w-full">
        {children}
        
        </section>
  

        </body>
        </RqWrapper>
    </html>
  );
}
